server {
    listen 80;
    listen [::]:80;
    server_name wardogs.kaermorh.cloud;

    location ^~ /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
        default_type text/plain;
    }

    location / {
        return 503;
    }
}
